const { ClassStats } = require('../models'); // placeholder route

const classData = [
  {
    id: 1,
    description: 'A fierce warrior of primitive background who can enter a battle rage',
    className: 'barbarian',
    strength: 16,
    dexterity: 14,
    constitution: 16,
    intelligence: 10,
    wisdom: 12,
    charisma: 8,
  },
  {
    id: 2,
    description: 'An inspiring magician whose power echoes the music of creation',
    className: 'bard',
    strength: 8,
    dexterity: 16,
    constitution: 14,
    intelligence: 10,
    wisdom: 12,
    charisma: 16,
  },{
    id: 3,
    description: 'A priestly champion who wields divine magic in service of a higher power',
    className: 'cleric',
    strength: 16,
    dexterity: 8,
    constitution: 14,
    intelligence: 10,
    wisdom: 16,
    charisma: 12,
  },{
    id: 4,
    description: 'A priest of the Old Faith, wielding the powers of nature — moonlight and plant growth, fire and lightning — and adopting animal forms',
    className: 'druid',
    strength: 8,
    dexterity: 14,
    constitution: 16,
    intelligence: 10,
    wisdom: 16,
    charisma: 12,
  },{
    id: 5,
    description: 'A holy warrior bound to a sacred oath',
    className: 'paladin',
    strength: 16,
    dexterity: 8,
    constitution: 14,
    intelligence: 10,
    wisdom: 12,
    charisma: 16,
  },{
    id: 6,
    description: 'A warrior who uses martial prowess and nature magic to combat threats on the edges of civilization',
    className: 'ranger',
    strength: 8,
    dexterity: 16,
    constitution: 14,
    intelligence: 10,
    wisdom: 16,
    charisma: 12,
  },{
    id: 7,
    description: 'A spellcaster who draws on inherent magic from a gift or bloodline',
    className: 'sorcerer',
    strength: 8,
    dexterity: 16,
    constitution: 14,
    intelligence: 10,
    wisdom: 12,
    charisma: 14,
  },{
    id: 8,
    description: 'A wielder of magic that is derived from a bargain with an extraplanar entity',
    className: 'warlock',
    strength: 8,
    dexterity: 16,
    constitution: 14,
    intelligence: 10,
    wisdom: 12,
    charisma: 16,
  },{
    id: 9,
    description: 'A scholarly magic-user capable of manipulating the structures of reality',
    className: 'wizard',
    strength: 8,
    dexterity: 16,
    constitution: 14,
    intelligence: 16,
    wisdom: 12,
    charisma: 8,
  },
];

const classes = () => db.bulkCreate(classData);

module.exports = classes;